import type { TestDefinitionInput } from '../schema';

export const definition: TestDefinitionInput = {
  id: 'lesson-01-test',
  title: 'اختبار الدرس الأول — الانسحاب وخواصه',
  scope: 'lesson',
  targetId: 'lesson-01-translation-and-properties',
  summary: 'اختبار أصلي شامل يغطي مفهوم الانسحاب، خواص الحفظ الأربع، وتمييز ما ليس انسحاباً.',
  instructions:
    'عشرون سؤالاً تقيس فهمك العميق للدرس الأول. يمكنك التنقّل بحرية بين الأسئلة ومراجعتها قبل الضغط على تسليم الاختبار. لن تظهر أية نتيجة أو تصحيح أثناء الإجابة.',
  passingScore: 60,
  solutionGroupSize: 5,
  questionIds: [
    'geo-l01-t01-q01',
    'geo-l01-t01-q02',
    'geo-l01-t01-q03',
    'geo-l01-t01-q04',
    'geo-l01-t01-q05',
    'geo-l01-t01-q06',
    'geo-l01-t01-q07',
    'geo-l01-t01-q08',
    'geo-l01-t01-q09',
    'geo-l01-t01-q10',
    'geo-l01-t01-q11',
    'geo-l01-t01-q12',
    'geo-l01-t01-q13',
    'geo-l01-t01-q14',
    'geo-l01-t01-q15',
    'geo-l01-t01-q16',
    'geo-l01-t01-q17',
    'geo-l01-t01-q18',
    'geo-l01-t01-q19',
    'geo-l01-t01-q20',
  ],
  blueprint: {
    coverage: [
      { concept: 'definition', label: 'مفهوم الانسحاب والتعريف الهندسي', count: 5 },
      { concept: 'direction-distance', label: 'الاتجاه والمسافة والمسارات', count: 4 },
      { concept: 'properties', label: 'خواص حفظ الأطوال والزوايا والمساحات والاستقامة', count: 7 },
      {
        concept: 'non-translation',
        label: 'تمييز الانسحاب ونفي ما ليس انسحاباً والتركيب',
        count: 4,
      },
    ],
    difficulty: [
      { level: 'basic', count: 5 },
      { level: 'medium', count: 8 },
      { level: 'advanced', count: 5 },
      { level: 'thinking', count: 2 },
    ],
    types: [
      { type: 'single-choice', count: 7 },
      { type: 'true-false', count: 3 },
      { type: 'multi-select', count: 2 },
      { type: 'numeric', count: 2 },
      { type: 'exact', count: 1 },
      { type: 'ordering', count: 1 },
      { type: 'matching', count: 1 },
      { type: 'classification', count: 1 },
      { type: 'error-analysis', count: 2 },
    ],
  },
};
