import type { AssessmentInput, ContentBlock } from '../schema';
const p = (text: string): ContentBlock[] => [{ type: 'paragraph', text }];
const c = (id: string, text: string) => ({ id, blocks: p(text) });
export const lesson04Assessment: AssessmentInput = {
  id: 'lesson-04-final-assessment',
  title: 'الاختبار النهائي — تطابق المثلثات',
  passingScore: 70,
  instructions:
    'أجب عن الأسئلة كلها، ويمكنك تعديل إجاباتك قبل التسليم. لن يظهر التصحيح إلا بعد تسليم الاختبار كاملاً.',
  questions: [
    {
      id: 'l4-q01-sas',
      type: 'multiple-choice',
      origin: 'authored',
      skill: 'ضلعان والزاوية المحصورة',
      prompt: p('أي معطيات تكفي لإثبات تطابق مثلثين؟'),
      choices: [
        c('l4-q01-a', 'تساوي طولي ضلعين وقياس الزاوية المحصورة بينهما مع مقابلاتها.'),
        c('l4-q01-b', 'تساوي زاوية واحدة فقط.'),
        c('l4-q01-c', 'تساوي محيطَي المثلثين فقط.'),
      ],
      correctChoiceId: 'l4-q01-a',
      explanation: p('هذه هي حالة ضلع–زاوية محصورة–ضلع.'),
    },
    {
      id: 'l4-q02-asa',
      type: 'true-false',
      origin: 'authored',
      skill: 'ضلع وزاويتان مجاورتان',
      prompt: p('يتطابق مثلثان إذا تساوى طول ضلع وقياسا الزاويتين المجاورتين له مع مقابلاتها.'),
      answer: true,
      explanation: p('هذه إحدى حالات التطابق الثلاث الواردة في الدرس.'),
    },
    {
      id: 'l4-q03-sss',
      type: 'multiple-choice',
      origin: 'authored',
      skill: 'الأضلاع الثلاثة',
      prompt: p('في مثلثين، الأطوال هي $3,4,5$ في كليهما. ما النتيجة؟'),
      choices: [
        c('l4-q03-a', 'المثلثان متطابقان بحالة تساوي الأضلاع الثلاثة.'),
        c('l4-q03-b', 'متشابهان فقط.'),
        c('l4-q03-c', 'لا يمكن الاستنتاج.'),
      ],
      correctChoiceId: 'l4-q03-a',
      explanation: p('تساوت أطوال الأضلاع الثلاثة مع مقابلاتها.'),
    },
    {
      id: 'l4-q04-correspondence',
      type: 'multiple-choice',
      origin: 'authored',
      skill: 'العناصر المتقابلة',
      prompt: p("إذا قابل $A$ النقطة $A'$، و$B$ النقطة $B'$، فأي ضلع يقابل $[AB]$؟"),
      choices: [c('l4-q04-a', "$[A'B']$"), c('l4-q04-b', "$[B'C']$"), c('l4-q04-c', "$[A'C']$")],
      correctChoiceId: 'l4-q04-a',
      explanation: p('طرفا الضلع ينتقلان إلى الطرفين المقابلين لهما.'),
    },
    {
      id: 'l4-q05-not-enough',
      type: 'true-false',
      origin: 'authored',
      skill: 'تمييز المعطيات الكافية',
      prompt: p('تساوي زاويتين فقط في مثلثين يكفي دائماً لإثبات تطابقهما.'),
      answer: false,
      explanation: p('خطأ شائع: الزاويتان تحددان الشكل لا الحجم؛ نحتاج ضلعاً مناسباً أيضاً.'),
    },
    {
      id: 'l4-q06-included',
      type: 'multiple-choice',
      origin: 'authored',
      skill: 'الزاوية المحصورة',
      prompt: p('ما الزاوية المحصورة بين الضلعين $[AB]$ و$[AC]$؟'),
      choices: [
        c('l4-q06-a', '$\\widehat{BAC}$'),
        c('l4-q06-b', '$\\widehat{ABC}$'),
        c('l4-q06-c', '$\\widehat{ACB}$'),
      ],
      correctChoiceId: 'l4-q06-a',
      explanation: p('رأس الضلعين المشترك هو $A$.'),
    },
    {
      id: 'l4-q07-third-angle',
      type: 'numeric',
      origin: 'authored',
      skill: 'مجموع زوايا المثلث',
      prompt: p('زاويتان في مثلث قياساهما $44^\\circ$ و$82^\\circ$. ما قياس الزاوية الثالثة؟'),
      answer: 54,
      tolerance: 0,
      unit: 'درجة',
      explanation: p('$180-44-82=54$.'),
    },
    {
      id: 'l4-q08-right-hypotenuse-leg',
      type: 'true-false',
      origin: 'authored',
      skill: 'المثلثات القائمة',
      prompt: p(
        'يتطابق مثلثان قائمان إذا تساوى وتر وضلع قائمة من أحدهما مع وتر وضلع قائمة من الآخر.',
      ),
      answer: true,
      explanation: p('هذه الحالة الخاصة مذكورة في نهاية الدرس.'),
    },
    {
      id: 'l4-q09-right-hypotenuse-angle',
      type: 'multiple-choice',
      origin: 'authored',
      skill: 'المثلثات القائمة',
      prompt: p('في مثلثين قائمين، تساوى الوتر وزاوية حادة. ما النتيجة؟'),
      choices: [
        c('l4-q09-a', 'المثلثان متطابقان.'),
        c('l4-q09-b', 'لا يمكن أن يتطابقا.'),
        c('l4-q09-c', 'يتساوى المحيط فقط.'),
      ],
      correctChoiceId: 'l4-q09-a',
      explanation: p('هذه الحالة الخاصة الثانية للمثلثين القائمين.'),
    },
    {
      id: 'l4-q10-definition',
      type: 'multiple-choice',
      origin: 'authored',
      skill: 'تعريف التطابق',
      prompt: p('ماذا يعني تطابق مثلثين؟'),
      choices: [
        c('l4-q10-a', 'تساوي عناصر أحدهما مع العناصر المقابلة لها في الآخر.'),
        c('l4-q10-b', 'تساوي مساحتيهما فقط.'),
        c('l4-q10-c', 'وجود زاوية مشتركة فقط.'),
      ],
      correctChoiceId: 'l4-q10-a',
      explanation: p('هذا هو تعريف التطابق الوارد في الكتاب، وعناصر المثلث هي أضلاعه وزواياه.'),
    },
  ],
};
